INSERT INTO permissions(perm_name, perm_description, createdAt, updatedAt) VALUES('user_add', 'Add User', now(), now());
INSERT INTO permissions(perm_name, perm_description, createdAt, updatedAt) VALUES('user_update', 'Update User', now(), now());
INSERT INTO permissions(perm_name, perm_description, createdAt, updatedAt) VALUES('user_get', 'Get User', now(), now());
INSERT INTO permissions(perm_name, perm_description, createdAt, updatedAt) VALUES('user_get_all', 'Get All User', now(), now());
INSERT INTO permissions(perm_name, perm_description, createdAt, updatedAt) VALUES('user_delete', 'Delete User', now(), now());
INSERT INTO permissions(perm_name, perm_description, createdAt, updatedAt) VALUES('role_add', 'Add Role', now(), now());
INSERT INTO permissions(perm_name, perm_description, createdAt, updatedAt) VALUES('role_update', 'Update Role', now(), now());
INSERT INTO permissions(perm_name, perm_description, createdAt, updatedAt) VALUES('role_get', 'Get Role', now(), now());
INSERT INTO permissions(perm_name, perm_description, createdAt, updatedAt) VALUES('role_get_all', 'Get All Role', now(), now());
INSERT INTO permissions(perm_name, perm_description, createdAt, updatedAt) VALUES('role_delete', 'Delete Role', now(), now());
INSERT INTO permissions(perm_name, perm_description, createdAt, updatedAt) VALUES('permissions_add', 'Add Permission', now(), now());
INSERT INTO permissions(perm_name, perm_description, createdAt, updatedAt) VALUES('permissions_update', 'Update Permission', now(), now());
INSERT INTO permissions(perm_name, perm_description, createdAt, updatedAt) VALUES('permissions_get', 'Get Permission', now(), now());
INSERT INTO permissions(perm_name, perm_description, createdAt, updatedAt) VALUES('permissions_get_all', 'Get All Permission', now(), now());
INSERT INTO permissions(perm_name, perm_description, createdAt, updatedAt) VALUES('permissions_delete', 'Delete Permission', now(), now());
INSERT INTO permissions(perm_name, perm_description, createdAt, updatedAt) VALUES('product_add', 'Add Product', now(), now());
INSERT INTO permissions(perm_name, perm_description, createdAt, updatedAt) VALUES('product_update', 'Update Product', now(), now());
INSERT INTO permissions(perm_name, perm_description, createdAt, updatedAt) VALUES('product_get', 'Get Product', now(), now());
INSERT INTO permissions(perm_name, perm_description, createdAt, updatedAt) VALUES('product_get_all', 'Get All Product', now(), now());
INSERT INTO permissions(perm_name, perm_description, createdAt, updatedAt) VALUES('product_delete', 'Delete Product', now(), now());